use ethers::types::{
    serde_helpers::deserialize_stringified_u64, Address, Bytes, TransactionReceipt, H256, U256,
};
use serde::{Deserialize, Serialize};

/// Details of a signed user operation
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, Default)]
pub struct UserOperation {
    /// The account initiating the UserOperation.
    #[serde(default = "ethers::types::Address::zero")]
    pub sender: Address,

    /// Nonce
    #[serde(default)]
    pub nonce: U256,

    /// Init code
    #[serde(rename = "initCode", default)]
    pub init_code: Bytes,

    /// Call data
    #[serde(rename = "callData", default)]
    pub call_data: Bytes,

    /// Call gas limit
    #[serde(rename = "callGasLimit", default)]
    pub call_gas_limit: U256,

    /// Verification gas limit
    #[serde(rename = "verificationGasLimit", default)]
    pub verification_gas_limit: U256,

    /// Pre-verification gas limit
    #[serde(rename = "preVerificationGas", default)]
    pub pre_verification_gas: U256,

    /// Represents the maximum amount that a user is willing
    /// to pay for their tx (inclusive of baseFeePerGas and maxPriorityFeePerGas).
    #[serde(rename = "maxFeePerGas", default)]
    pub max_fee_per_gas: U256,

    /// Represents the maximum tx fee that will go to the miner as part of the user's
    #[serde(rename = "maxPriorityFeePerGas", default)]
    pub max_priority_fee_per_gas: U256,

    /// Paymaster data
    #[serde(rename = "paymasterAndData", default)]
    pub paymaster_and_data: Bytes,

    /// User op signature
    #[serde(default)]
    pub signature: Bytes,

    #[serde(default = "ethers::types::Address::zero", rename = "entryPoint")]
    /// Entry point address
    pub entry_point: Address,

    /// Block hash. None when pending.
    #[serde(default, rename = "blockHash")]
    pub block_hash: Option<H256>,

    /// Number of the block this user operation was included within.
    #[serde(default, rename = "blockNumber")]
    pub block_number: Option<u64>, // stackup return as integer whereas alchemy defines it has hex / U64.

    /// Transaction hash
    #[serde(default, rename = "transactionHash")]
    pub transaction_hash: Option<H256>,
}

/// Details of an executed user operation
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, Default)]
pub struct UserOperationReceipt {
    /// The request hash of the UserOperation.
    #[serde(default, rename = "userOpHash")]
    pub user_op_hash: H256,

    /// The entrypoint address the request should be sent through.
    #[serde(default = "ethers::types::Address::zero", rename = "entryPoint")]
    pub entry_point: Address,

    /// The account initiating the UserOperation.
    #[serde(default = "ethers::types::Address::zero")]
    pub sender: Address,

    /// The paymaster used for this UserOperation (or empty).
    #[serde(default = "ethers::types::Address::zero")]
    pub paymaster: Address,

    /// Nonce
    pub nonce: U256,

    /// The actual amount paid (by account or paymaster) for this UserOperation.
    #[serde(rename = "actualGasCost", default)]
    pub actual_gas_cost: U256,

    /// The total gas used by this UserOperation (including preVerification, creation, validation, and execution).
    #[serde(rename = "actualGasUsed", default)]
    pub actual_gas_used: U256,

    /// Whether the user operation succeeded or failed.
    pub success: bool,

    /// Indicates whether the execution completed without reverting.
    pub reason: Option<String>,

    /// The logs generated by this UserOperation.
    pub logs: Vec<UserOperationLog>,

    /// The TransactionReceipt object for the entire bundle, not only for this UserOperation.
    pub receipt: TransactionReceipt,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, Default)]
pub struct UserOperationLog {
    address: Address,
    topics: Vec<String>,
    data: String,
    #[serde(rename = "blockNumber", default)]
    pub block_number: U256,
    #[serde(rename = "transactionHash", default)]
    pub transaction_hash: H256,
    #[serde(rename = "transactionIndex", default)]
    pub transaction_index: String,
    #[serde(rename = "blockHash", default)]
    pub block_hash: H256,
    #[serde(rename = "logIndex", default)]
    pub log_index: String,
    removed: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize, Default)]
pub struct UserOperationGasEstimate {
    /// Pre-verification gas
    #[serde(deserialize_with = "deserialize_stringified_u64")]
    #[serde(rename = "preVerificationGas")]
    pub pre_verification_gas: u64,

    /// Verification gas
    #[serde(deserialize_with = "deserialize_stringified_u64")]
    #[serde(rename = "verificationGasLimit")]
    pub verification_gas_limit: u64,

    /// Call gas limit
    #[serde(deserialize_with = "deserialize_stringified_u64")]
    #[serde(rename = "callGasLimit")]
    pub call_gas_limit: u64,
}
